[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key"
