-- Insert sample resources without requiring a specific user
-- We'll use NULL for uploaded_by initially, then update policies to allow this
INSERT INTO public.resources (
  name, description, file_url, file_type, file_size, category, 
  uploaded_by, downloads, rating, rating_count, is_featured
) VALUES 
(
  'Advanced Calculus Fundamentals',
  'Comprehensive guide to advanced calculus concepts including limits, derivatives, and integrals. Perfect for undergraduate mathematics students.',
  '/placeholder.svg?height=400&width=300&text=Calculus+PDF',
  'pdf',
  2457600,
  'Mathematics',
  NULL,
  1247,
  4.8,
  156,
  true
),
(
  'Quantum Physics Introduction',
  'Explore the fascinating world of quantum mechanics and particle physics. Covers wave-particle duality, uncertainty principle, and quantum states.',
  '/placeholder.svg?height=400&width=300&text=Quantum+Physics',
  'pdf',
  3251200,
  'Physics',
  NULL,
  892,
  4.6,
  98,
  false
),
(
  'Interactive World History Timeline',
  'Visual timeline showcasing major world events from ancient civilizations to modern times. Interactive elements help students understand historical connections.',
  '/placeholder.svg?height=400&width=300&text=History+Timeline',
  'image',
  1887436,
  'History',
  NULL,
  2156,
  4.9,
  203,
  true
),
(
  'Chemistry Lab Safety Protocol',
  'Essential safety procedures and protocols for chemistry laboratory work. Includes emergency procedures, equipment handling, and chemical storage guidelines.',
  '/placeholder.svg?height=400&width=300&text=Lab+Safety',
  'video',
  47185920,
  'Chemistry',
  NULL,
  567,
  4.7,
  67,
  false
),
(
  'Classic Literature Anthology',
  'Curated collection of timeless literary masterpieces and analysis. Features works from Shakespeare, Dickens, Austen, and other renowned authors.',
  '/placeholder.svg?height=400&width=300&text=Literature+Collection',
  'document',
  5872025,
  'Literature',
  NULL,
  1834,
  4.5,
  145,
  false
),
(
  'Cell Biology Structure Guide',
  'Detailed presentation on cellular anatomy, organelles, and biological processes. Includes high-resolution diagrams and interactive elements.',
  '/placeholder.svg?height=400&width=300&text=Cell+Biology',
  'presentation',
  8601600,
  'Biology',
  NULL,
  743,
  4.4,
  89,
  false
),
(
  'Programming Fundamentals in Python',
  'Complete beginner guide to Python programming. Covers variables, functions, loops, and object-oriented programming concepts.',
  '/placeholder.svg?height=400&width=300&text=Python+Programming',
  'pdf',
  4123456,
  'Computer Science',
  NULL,
  3421,
  4.7,
  287,
  true
),
(
  'Renaissance Art History',
  'Comprehensive study of Renaissance art movements, key artists, and cultural impact. Features high-quality reproductions of famous works.',
  '/placeholder.svg?height=400&width=300&text=Renaissance+Art',
  'presentation',
  12345678,
  'Art',
  NULL,
  1567,
  4.6,
  134,
  false
),
(
  'World Geography Atlas',
  'Interactive atlas covering physical geography, climate patterns, and cultural regions. Includes detailed maps and statistical data.',
  '/placeholder.svg?height=400&width=300&text=Geography+Atlas',
  'image',
  9876543,
  'Geography',
  NULL,
  2234,
  4.8,
  198,
  true
),
(
  'Music Theory Fundamentals',
  'Essential music theory concepts including scales, chords, rhythm, and composition techniques. Audio examples included.',
  '/placeholder.svg?height=400&width=300&text=Music+Theory',
  'audio',
  15432109,
  'Music',
  NULL,
  987,
  4.5,
  76,
  false
),
(
  'Organic Chemistry Reactions',
  'Comprehensive guide to organic chemistry reactions, mechanisms, and synthesis pathways. Includes practice problems and solutions.',
  '/placeholder.svg?height=400&width=300&text=Organic+Chemistry',
  'pdf',
  6789012,
  'Chemistry',
  NULL,
  1456,
  4.6,
  112,
  false
),
(
  'European History 1800-1900',
  'Detailed analysis of 19th century European political, social, and economic developments. Covers major wars, revolutions, and cultural changes.',
  '/placeholder.svg?height=400&width=300&text=European+History',
  'document',
  3456789,
  'History',
  NULL,
  987,
  4.4,
  89,
  false
),
(
  'Data Structures and Algorithms',
  'Essential computer science concepts covering arrays, linked lists, trees, graphs, sorting, and searching algorithms with code examples.',
  '/placeholder.svg?height=400&width=300&text=Data+Structures',
  'pdf',
  5432109,
  'Computer Science',
  NULL,
  2345,
  4.8,
  201,
  true
),
(
  'Modern Art Movements',
  'Exploration of 20th century art movements including Impressionism, Cubism, Surrealism, and Abstract Expressionism.',
  '/placeholder.svg?height=400&width=300&text=Modern+Art',
  'presentation',
  8765432,
  'Art',
  NULL,
  1234,
  4.5,
  98,
  false
),
(
  'Physical Geography Fundamentals',
  'Study of Earth physical features, climate systems, and natural processes. Includes topographic maps and satellite imagery.',
  '/placeholder.svg?height=400&width=300&text=Physical+Geography',
  'image',
  7654321,
  'Geography',
  NULL,
  1678,
  4.7,
  145,
  false
),
(
  'Introduction to Microeconomics',
  'Basic economic principles covering supply and demand, market structures, consumer behavior, and production theory.',
  '/placeholder.svg?height=400&width=300&text=Microeconomics',
  'pdf',
  4567890,
  'Economics',
  NULL,
  1890,
  4.6,
  167,
  false
),
(
  'Shakespeare Complete Works',
  'Complete collection of William Shakespeare plays and sonnets with modern annotations and historical context.',
  '/placeholder.svg?height=400&width=300&text=Shakespeare',
  'document',
  8901234,
  'Literature',
  NULL,
  2567,
  4.9,
  234,
  true
),
(
  'Linear Algebra Essentials',
  'Fundamental concepts of linear algebra including vectors, matrices, eigenvalues, and linear transformations.',
  '/placeholder.svg?height=400&width=300&text=Linear+Algebra',
  'pdf',
  3678901,
  'Mathematics',
  NULL,
  1345,
  4.7,
  123,
  false
),
(
  'Environmental Science Overview',
  'Comprehensive study of environmental systems, ecology, pollution, climate change, and sustainability practices.',
  '/placeholder.svg?height=400&width=300&text=Environmental+Science',
  'presentation',
  6789123,
  'Science',
  NULL,
  1123,
  4.5,
  98,
  false
),
(
  'Classical Music History',
  'Journey through classical music from Baroque to Romantic periods. Includes audio examples and composer biographies.',
  '/placeholder.svg?height=400&width=300&text=Classical+Music',
  'audio',
  12345678,
  'Music',
  NULL,
  876,
  4.6,
  87,
  false
);

-- Add some additional categories to make the platform more comprehensive
INSERT INTO public.resources (
  name, description, file_url, file_type, file_size, category, 
  uploaded_by, downloads, rating, rating_count, is_featured
) VALUES 
(
  'Introduction to Psychology',
  'Basic psychological concepts covering cognition, behavior, development, and mental health fundamentals.',
  '/placeholder.svg?height=400&width=300&text=Psychology',
  'pdf',
  5234567,
  'Psychology',
  NULL,
  1567,
  4.6,
  134,
  false
),
(
  'World Languages Primer',
  'Introduction to major world languages including grammar basics, cultural context, and learning strategies.',
  '/placeholder.svg?height=400&width=300&text=Languages',
  'document',
  4345678,
  'Languages',
  NULL,
  1234,
  4.4,
  89,
  false
),
(
  'Philosophy Through the Ages',
  'Survey of philosophical thought from ancient Greece to modern times. Covers major philosophers and their ideas.',
  '/placeholder.svg?height=400&width=300&text=Philosophy',
  'pdf',
  6456789,
  'Philosophy',
  NULL,
  987,
  4.7,
  76,
  false
),
(
  'Engineering Fundamentals',
  'Basic engineering principles covering mechanics, materials, design process, and problem-solving methodologies.',
  '/placeholder.svg?height=400&width=300&text=Engineering',
  'presentation',
  7567890,
  'Engineering',
  NULL,
  1456,
  4.8,
  112,
  true
),
(
  'Business Management Basics',
  'Essential business concepts including leadership, strategy, operations, marketing, and financial management.',
  '/placeholder.svg?height=400&width=300&text=Business',
  'document',
  3789012,
  'Business',
  NULL,
  2134,
  4.5,
  178,
  false
);
